[package]
name = "kcacheext"
version = "0.3.1"
authors = ["Marco Grassi <marco.gra@gmail.com>"]
edition = "2021"

[dependencies]
clap = "4.0.12"
bytesize = "1.1.0"
packed_struct = "0.10.0"
packed_struct_codegen = "0.10.0"
byteorder = "1.4.3"
lzfse = "0.1.0"
